### ISSUE TITLE
Disconnected State (Home page) says "Retro Funding 6: OP Stack"

### ISSUE THREAD

**Issue by shaunop** [grants-stack-frontier/op-rf-6#69] opened 2024-10-25 18:09 UTC
### What was the URL where the error occurred?

https://develop-op-rf-6.up.railway.app/

### What happened?

The home page (disconnected) currently says "Retro Funding Round 6: OP Stack"
<img width="720" alt="Screenshot 2024-10-25 at 11 07 38 AM" src="https://github.com/user-attachments/assets/f8d601ab-e6c9-4f51-abde-c049c718f056">

### What should have happened instead?

It should say "Retro Funding 6: Governance" . Remove the word Round from the title. Add Governance.

### Steps to Reproduce

Disconnect wallet and view homepage.

**Comment by meglister** [comment] 2024-10-25 18:52
think this is a dupe of #62 -- @geovgy pls close if true

**Comment by geovgy** [comment] 2024-10-25 18:54
True

**Closed as completed by geovgy** 2024-10-25 18:54 UTC
Labels: bug
